"""Added groups and areas tables

Revision ID: 011d03050529
Revises: b8eb500a0f55
Create Date: 2019-07-21 18:07:57.189273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "011d03050529"
down_revision = "b8eb500a0f55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="user_manager",
    )
    op.create_table(
        "groups",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("expiration_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="user_manager",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("groups", schema="user_manager")
    op.drop_table("areas", schema="user_manager")
    # ### end Alembic commands ###
