"""Added group_area table

Revision ID: 097048438d37
Revises: 011d03050529
Create Date: 2019-07-21 18:09:19.758267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "097048438d37"
down_revision = "011d03050529"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_area",
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["area_id"], ["user_manager.areas.id"]),
        sa.ForeignKeyConstraint(["group_id"], ["user_manager.groups.id"]),
        schema="user_manager",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_area", schema="user_manager")
    # ### end Alembic commands ###
