"""Added users.is_activated property

Revision ID: 28c72eab7983
Revises: 097048438d37
Create Date: 2019-07-21 18:13:10.920773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "28c72eab7983"
down_revision = "097048438d37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_activated", sa.Boolean(), nullable=False),
        schema="user_manager",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_activated", schema="user_manager")
    # ### end Alembic commands ###
