"""Added group_user table

Revision ID: 3ad78b0a3936
Revises: 28c72eab7983
Create Date: 2019-07-21 18:15:59.948803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ad78b0a3936"
down_revision = "28c72eab7983"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_user",
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["user_manager.groups.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user_manager.users.id"]),
        schema="user_manager",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_user", schema="user_manager")
    # ### end Alembic commands ###
