"""Removed useless property in group table

Revision ID: 693d47d886c7
Revises: 3ad78b0a3936
Create Date: 2019-07-21 18:18:36.253558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "693d47d886c7"
down_revision = "3ad78b0a3936"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "last_name", schema="user_manager")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="user_manager",
    )
    # ### end Alembic commands ###
