"""Added expiration_date

Revision ID: b8eb500a0f55
Revises: 0c84e60df5bc
Create Date: 2019-07-21 17:46:56.854619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b8eb500a0f55"
down_revision = "0c84e60df5bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("expiration_date", sa.DateTime(), nullable=False),
        schema="user_manager",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "expiration_date", schema="user_manager")
    # ### end Alembic commands ###
